name: windows
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [amd64]
        ssl: [ ON ]   
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');   
          env: 
            VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

      # - uses: xmake-io/github-action-setup-xmake@v1
      #   with:
      #     xmake-version: branch@dev
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      # - name: download mysql
      #   run: |
      #      powershell Invoke-WebRequest -OutFile mysql.zip https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.35-winx64.zip
      #      unzip mysql.zip
      #      Move-Item -Path ./mysql-8.0.35-winx64/include -Destination ./
      #      Move-Item -Path ./mysql-8.0.35-winx64/lib -Destination ./ 
      #     ls include
      - name: List files in the repository
        run: |
          unzip asio.zip
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."  
      - name: Build
        run: |
          cmake .
          make
          # xmake f -a x64 -y
          # xmake
